# Site Info
title:              "The Plain"
description:        "My First Blog Forked from The Plain - A minimalist Jekyll theme"
author_name:        "Qiang" # change this to your name
logo_url:           Qiang_cover.jpg # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://csu1505110121.github.io # main url
baseurl:            /the-plain
permalink:          /:title # Post permalink
timezone:           Asia/Kuala_Lumpur # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-remote-theme

remote-theme: heiswayi/the-plain

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
